spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=tue&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: postgres123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
